service: buy-the-dip

custom:
  cloudWatchLogsTags:
    TagName1: buy-the-dip-${env:STAGE}

plugins:
  - "serverless-plugin-typescript"
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-tag-cloud-watch-logs

useDotenv: true

provider:
  name: aws
  region: ${env:SERVERLESS_REGION}
  stage: ${env:STAGE}
  runtime: nodejs14.x
  deploymentBucket:
    name: ${env:SERVERLESS_S3_BUCKET_PREFIX}-${env:STAGE}

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
