name: add-daily-stock

on:
  schedule:
    - cron: "0 16 * * 1-5"

jobs:
  cron:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Pacaksges
        run: npm install
      - name: insert secret to env
        run: |
          echo DATABASE_HOST=${{ secrets.DATABASE_HOST }}    >> .env
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }}    >> .env
          echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}    >> .env
          echo DATABADATABASE_PASSWORDSE_HOST=${{ secrets.DATABADATABASE_PASSWORDSE_HOST }}    >> .env
          echo DATABASE_DATABASE_NAME=${{ secrets.DATABASE_DATABASE_NAME }}    >> .env
          echo STAGE=${{ secrets.STAGE }}    >> .env
      - name: CI
        run: |
          npm ci
      - name: Run Cron
        run: |
          yarn insert-daily-data
