name: deploy serverless
on:
    push:
        branches:
            - main
jobs:
    Deploy-Serverless:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Install Pacaksges
              run: yarn install
            - name: serverless deploy
              uses: serverless/github-action@v3
              with:
                  args: deploy
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  STAGE: ${{ secrets.STAGE }}
