name: deploy serverless dev
on:
  push:
    branches:
      - dev
jobs:
  Deploy-Serverless:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Pacaksges
        run: yarn install
      - name: insert secret to env
        run: |
          echo ${{ secrets.DATABASE_HOST }}    >> .env
          echo ${{ secrets.DATABASE_PORT }}    >> .env
          echo ${{ secrets.DATABASE_USERNAME }}    >> .env
          echo ${{ secrets.DATABADATABASE_PASSWORDSE_HOST }}    >> .env
          echo ${{ secrets.DATABASE_DATABASE_NAME }}    >> .env
          echo ${{ secrets.STAGE }}    >> .env
      - name: test insert daily
        run: yarn insert-daily-data
      # - name: serverless deploy
      #   uses: serverless/github-action@v3
      #   with:
      #     args: deploy
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     STAGE: ${{ secrets.STAGE }}
      #     SERVERLESS_REGION: ${{ secrets.SERVERLESS_REGION }}
      #     SERVERLESS_S3_BUCKET_PREFIX: ${{ secrets.SERVERLESS_S3_BUCKET_PREFIX }}
