name: deploy serverless dev
on:
  push:
    branches:
      - dev

jobs:
  development-deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: yarn install
      - name: insert secret to env
        run: |
          echo DATABASE_HOST=${{ secrets.DATABASE_HOST }}   >> .env
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }}    >> .env
          echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}   >> .env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}    >> .env
          echo DATABASE_DATABASE_NAME=${{ secrets.DATABASE_DATABASE_NAME }}   >> .env
          echo STAGE=${{ secrets.STAGE }}    >> .env
      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
