name: deploy serverless
on:
    push:
        branches:
            - main
jobs:
    Deploy-Serverless:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Install Pacaksges
              run: yarn install
             - name: insert secret to env
              run: |
                echo DATABASE_HOST=${{ env.DATABASE_HOST }}    >> .env
                echo DATABASE_PORT=${{ env.DATABASE_PORT }}    >> .env
                echo DATABASE_USERNAME=${{ env.DATABASE_USERNAME }}    >> .env
                echo DATABADATABASE_PASSWORDSE_HOST=${{ env.DATABADATABASE_PASSWORDSE_HOST }}    >> .env
                echo DATABASE_DATABASE_NAME=${{ env.DATABASE_DATABASE_NAME }}    >> .env
                echo STAGE=${{ env.STAGE }}    >> .env
            - name: serverless deploy
              uses: serverless/github-action@v3
              with:
                  args: deploy

